### ISSUE TITLE
Hello man

### ISSUE THREAD

**Issue by RallyTuning** [theodorzoulias/ParallelLoopLibrary#4]
Hello, sorry for disturbing you here. But i need your help about the project you answered me on Stackoverflow. The fact is that i can't **unload** the dll that are run in a TaskQueue _(Commandos, remember?)_. My detailed questions is here: https://stackoverflow.com/questions/75289946/c-sharp-unload-unmanaged-assembly-dll-library
Thanks 🙏🏻

**Comment by theodorzoulias** [comment]
Hi Gianluigi, I just saw your email. Unfortunately I don't know the answer to your question. Btw if you add @TheodorZoulias in any comment in StackOverflow, I am getting a notification. So you can alert methis way for questions that I might be able to help.

Best regards, Theodor.

**Comment by RallyTuning** [comment]
Thanks anyway :)
